name: CI
on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@v1
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
    - uses: workarea-commerce/ci/rubocop@v1
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
    - uses: workarea-commerce/ci/eslint@v1
      with:
        args: '**/*.js'

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:admin
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
        SENTRY_DSN: ${{ secrets.sentry_dsn }}

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:core
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
        SENTRY_DSN: ${{ secrets.sentry_dsn }}

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:storefront
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
        SENTRY_DSN: ${{ secrets.sentry_dsn }}

  plugins_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:plugins
      env:
        BUNDLE_GEMS__WEBLINC__COM: ${{ secrets.gem_credentials }}
        SENTRY_DSN: ${{ secrets.sentry_dsn }}
